name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Save
        run: echo "BLAH=${{ secrets.BLAH }}" >> $GITHUB_ENV

  test1:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print
        run: echo "Print ${{ env.BLAH }}"
